// This file is automatically generated by Next.js
// Do not edit this file manually

import type { NextConfig } from "next"

const nextConfig: NextConfig = {
  output: "export",
  trailingSlash: true,
}

export default nextConfig
