// This file is automatically generated by Next.js
// Do not edit this file manually

export default function config() {
  return {
    basePath: "",
    assetPrefix: "",
    images: {
      domains: [],
      remotePatterns: []
    },
    trailingSlash: false,
    i18n: null
  }
}
